### ISSUE TITLE
Missing textures for parallax mapping example

### ISSUE THREAD

**Issue by stetre** [PacktPublishing/OpenGL-4-Shading-Language-Cookbook-Third-Edition#2]
Hi, it looks like the textures used in the parallax mapping example (chapter 5, sceneparallax.cpp) are missing from the repository.

**Comment by daw42** [comment]
Thanks for the report.  I'll look into that as soon as I can.

**Comment by stetre** [comment]
Thank you. The file path to the cube map in scenereflectcube.cpp and scenerefractcube.cpp is also slightly off (`/pisa-hdr-512/` instead of `/pisa-hdr/`).

**Comment by daw42** [comment]
Thanks again for the report.  The images should be available now.
