### ISSUE TITLE
cmake configure error in windows

### ISSUE THREAD

**Issue by zekeliu** [PacktPublishing/OpenGL-4-Shading-Language-Cookbook-Third-Edition#7]
error: 

CMake Error at CMakeLists.txt:18 (find_package):
  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.

i can cmake glm package sucessfully but do not get the two cmake files below.  this is in windows. not linux or mac.  i am using cmake gui version.

**Comment by observant2** [comment]
How did you solve this? 🤔

**Comment by chihanpeng** [comment]
Please, how did you solve this? 

On Windows platform, I thoroughly followed the README.md in the example code. I downloaded the lastest GLM source. I could use CMAKE to run the CMakeLists.txt in the GLM source and eventually created a bunch of Visual Studio solution / projection files. Everything in CMake ran smoothly. But alas, there is no `glmConfig.cmake` nor `glmConfigVersion.cmake` created! 

How to get these `glmConfig.cmake` nor `glmConfigVersion.cmake` files generated?

**Comment by thatrobotguy** [comment]
I have not tried running this code on Windows (Ubuntu 1804 is my os), but I think there is a main directory with all of the header files.
In fact, there is a header file that imports all other glm files They even state in the docs, line `173` of `manual.md`:
```
GLM is a header-only library, and thus does not need to be compiled. We can use GLM's implementation of GLSL's mathematics functionality by including the `<glm/glm.hpp>` header:
```
This call:
```cpp
#include <glm/glm.hpp>
```
You should be able to just point here and you are golden. Just add it as a source file in `add_executable` or `target_compile_sources`.
You will need to run a `include_directories` or `target_include_directories` before this will work.
Reply how it goes.

**Comment by daw42** [comment]
Getting Cmake to find GLM can be a pain.  Also, it looks like upstream GLM may have changed the Cmake interface.  https://github.com/g-truc/glm/pull/963.  I'll look into this when I have a Windows machine available.

**Comment by thatrobotguy** [comment]
Hey
How did you install `glm`?
I use `vcpkg` from [here](https://github.com/microsoft/vcpkg) and I was able to install the packages required.
Here is what the new main `CMakeLists.txt` looks like:
```
# On MSVC, use the vcpkg package manager to install glm. first, we have to use the toolchain file included with vcpkg to import it properly.
if(WIN32 OR MSVC)
  # You will have to set this path to your specific location on your Windows machine
  set(CMAKE_TOOLCHAIN_FILE C:/vcsrc/vcpkg/scripts/buildsystems/vcpkg.cmake)
endif(WIN32 OR MSVC)

cmake_minimum_required (VERSION 3.0)

set (CMAKE_CXX_STANDARD 17)
set(CXX_STANDARD_REQUIRED ON)

project (GLSLCOOKBOOK)

if(MSVC)
  add_definitions(/DNOMINMAX)
endif()

if(UNIX)
    message(STATUS "Running Linux compiling. Options [GLVND] for modern OpenGL or [LEGACY] for historical OpenGl.")
    message(STATUS "Setting GLVND option.")
    set(OpenGL_GL_PREFERENCE GLVND)
endif()

find_package( glm CONFIG REQUIRED )
find_package( glfw3 CONFIG REQUIRED )
find_package( OpenGL REQUIRED )

include_directories( ingredients )

add_subdirectory( ingredients )
add_subdirectory( chapter01 )
add_subdirectory( chapter02 )
add_subdirectory( chapter03 )
add_subdirectory( chapter04 )
add_subdirectory( chapter05 )
add_subdirectory( chapter06 )
add_subdirectory( chapter07 )
add_subdirectory( chapter08 )
add_subdirectory( chapter09 )
add_subdirectory( chapter10 )
add_subdirectory( chapter11 )

file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/media DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
```
I then compile the code with these commands in the root of the code repo:
```
mkdir cmake-build
cd cmake-build
cmake ..
cd ..
cmake --build cmake-build/ --
```
Basically, `vcpkg` handles all of the garbage you don't want to think about, kind of like a Linux environment. They have instructions on installing packages, but `glm` is installed like this:
```
.\vcpkg.exe install glm
```
Also, notice where I put the `vcpkg` repository. It is in a subdirectory right off of the `C:` drive.
You then need to make sure you have a visual studio version installed to have a proper compiler and you should be good to go.

**Comment by Aeranuth** [comment]
anyone solved this issue? when i run cmake, i got a glm_DIR NOT_FOUND error.

**Comment by allenk** [comment]
Just like @thatrobotguy  solution. I think The best solution for windows is using vcpkg.
I fork the repo and add a vcpkg solution:
[vcpkg for glm, glfw3](https://github.com/allenk/OpenGL-4-Shading-Language-Cookbook-Third-Edition/blob/master/README.md)

Launch CMake. Select example code folder.
In CMake UI, add Entry for cmake toolchain.
CMAKE_TOOLCHAIN_FILE, C:/vcpkg/scripts/buildsystems/vcpkg.cmake

**Comment by daw42** [comment]
@allenk  Would you be willing to make pull-request for this feature?  Thanks.

**Comment by corybarr** [comment]
> Just like @thatrobotguy solution. I think The best solution for windows is using vcpkg.
> I fork the repo and add a vcpkg solution:
> [vcpkg for glm, glfw3](https://github.com/allenk/OpenGL-4-Shading-Language-Cookbook-Third-Edition/blob/master/README.md)
> 
> Launch CMake. Select example code folder.
> In CMake UI, add Entry for cmake toolchain.
> CMAKE_TOOLCHAIN_FILE, C:/vcpkg/scripts/buildsystems/vcpkg.cmake

@allenk Thank you. That was such a huge help. I struggled for a long, long time trying to get CMake working on Windows with this repo.

**Comment by daw42** [comment]
@allenk @corybarr Glad you got it working.  I'm happy to consider a pull request with this fix.  Thanks!
