### ISSUE TITLE
Suggestions and feedback broken link

### ISSUE THREAD

**Issue by tim-rex** [PacktPublishing/OpenGL-4-Shading-Language-Cookbook-Third-Edition#9]
The link to "suggestions and feedback" at the bottom of the README.md is broken.

https://docs.google.com/forms/d/e/1FAIpQLSdy7dATC6QmEL81FIUuymZ0Wy9vH1jHkvpY57OiMeKGqib_Ow/viewform

Is there anywhere else I can send suggestions/feedback?
I'm getting a lot out of the book, it's proving to be a vauable resource. 
I would suggest a more thorough discussion of SPIRV shaders for use in OpenGL.

One of the reasons I purchased this book was because of the following on the amazon page:
**What you will learn**
 - Understand physically based reflection models and the SPIR-V Shader binary

But the discussion of SPIRV feels a little lacking, partly because in practice - getting SPIRV shaders working correctly on OpenGL is a bit of a fools errand, with support across vendors and platforms seeming to be incredibly lacking/broken.

It also makes no mention that raw uniforms are not supported, in favour of uniform buffer objects.

**Comment by shubham763** [comment]
Hi @tim-rex 
We're looking into the broken link issue.
You can use this email as an alternative feedback link: customercare@packtpub.com
Thanks!
